syntax = "proto3";
import "google/protobuf/timestamp.proto";

option csharp_namespace = "the_identity";

package identity;

// The greeting service definition.
service IdentityService {
  // Sends a greeting
  rpc approvePII (approvePIIReq) returns (approvePIIRes);
  rpc generateShadowID (generateShadowIDReq) returns (generateShadowIDRes);
  rpc encryptedPII (encryptedPIIReq) returns (encryptedPIIRes);
  rpc decryptPII (decryptPIIReq) returns (decryptPIIRes);
  rpc hashSearchKey (hashSearchKeyReq) returns (hashSearchKeyRes);
  rpc revokePII (revokePIIReq) returns (revokePIIRes);
  rpc validateIdentity (validateIdentityReq) returns (validateIdentityRes);
}

message approvePIIReq {
  string tenant = 1;
  string requestShadowID = 2;
  string applicantName = 3;
  string reason = 4;
}

message approvePIIRes {
  string tenant = 1;
  string requestShadowID = 2;
  google.protobuf.Timestamp timestamp = 3;
}

message generateShadowIDReq {
  string tenant = 1;
  string requestShadowID = 2;
  bool isDomestic = 3;
  bool isIntern = 4;
  bool isResearch = 5;
  int32 enrolYear = 6;
  optional bool isFulltime = 7; // Domestic only
}

message generateShadowIDRes {
  string tenant = 1;
  string requestShadowID = 2;
  string newShadowID = 3;
}

message encryptedPIIReq {
  string tenant = 1;
  string requesterShadowID = 2; // Who request PII encryption?
  string ownerShadowID = 3; // Who is the Genuine Owner?
  string firstname = 4;
  string lastname = 5; 
  string DOB = 6; 
  string phone = 7; 
  string uniEmail = 8; 
  string personalEmail = 9; 
  string address = 10; 
  string uniID = 11;
  string nationalID = 12;
  string nationality = 13;
  string passportID = 14;
}

message encryptedPIIRes {
  string tenant = 1;
  string requesterShadowID = 2;
  bytes encryptedPIIBlob = 3;
  string statusMessage = 4;
}

message decryptPIIReq {
  string tenant = 1;
  string requesterShadowID = 2;
  string requesterPosition = 3;
  string ownerShadowID = 4;
  string reason = 5;
}

message decryptPIIRes {
  string tenant = 1;
  bool isAuthorised = 2;
  bool success = 3;
  string errorMessage = 4;
}

message hashSearchKeyReq {
  string tenant = 1;
  string requesterShadowID = 2; // Record who request?
  string ownerShadowID = 3; // Who owns PII?
  string name = 4;
  string uniEmail = 5;
  string DOB = 6;
  string uniID = 7;
}

message hashSearchKeyRes {
  string tenant = 1;
  bytes hashedName = 2;
  bytes hashedUniEmail = 3;
  bytes hashedDOB = 4;
  bytes hashedUniID = 5;
}

message revokePIIReq {
  string tenant = 1;
  string requestShadowID = 2;
  string ownerShadowID = 3;
  string requesterPosition = 4;
  bytes evidences = 5;
  string reason = 6;
}

message revokePIIRes {
  string tenant = 1;
  google.protobuf.Timestamp timestamp = 2;
  bool status = 3;
  bool isAuthority = 4; // Refer to the requester has authority to revoke PII or not.
  string responseMessage = 5;
  bool isIllegal = 6; // The reason related to the owner illegal act or not, such as impersonate or forged government documents.
}

message validateIdentityReq {
  string tenant = 1;
  string requesterShadowID = 2; 
  string requesterPosition = 3;
  bytes hashedUniID = 4;
  bytes hashedName = 5;
  optional bytes hashedUniEmail = 6;
  optional bytes hashedDOB = 7;
}

message validateIdentityRes {
  string tenant = 1;
  string requesterShadowID = 2;
  bool isAuthorised = 3;
  bool success = 4;
  optional string shadowID = 5;
  string errorMessage = 6;
}