syntax = "proto3";
import "google/protobuf/timestamp.proto";

option csharp_namespace = "the_identity";

package identity;

// The greeting service definition.
service IdentityService {
  // Sends a greeting
  rpc approvePII (approvePIIReq) returns (approvePIIRes);
  rpc generateShadowID (generateShadowIDReq) returns (generateShadowIDRes);
  rpc encryptedPII (encryptedPIIReq) returns (encryptedPIIRes);
  rpc decryptPII (decryptPIIReq) returns (decryptPIIRes);
  rpc hashSearchKey (hashSearchKeyReq) returns (hashSearchKeyRes);
  rpc revokePII (revokePIIReq) returns (revokePIIRes);
  rpc validateIdentity (validateIdentityReq) returns (validateIdentityRes);
}

message approvePIIReq {
  string tenant = 1;
  string requesterShadowID = 2;
  string applicantName = 3;
  string role = 4;
  string reason = 5;
}

message approvePIIRes {
  string tenant = 1;
  string requesterShadowID = 2;
  google.protobuf.Timestamp timestamp = 3;
  bool status = 4;
  optional string errorMessage = 5;
}

message generateShadowIDReq {
  string tenant = 1;
  string requestShadowID = 2;
  bool isDomestic = 3;
  bool isIntern = 4;
  bool isResearch = 5;
  bool isExchange = 6;
  int32 enrolYear = 7;
  optional bool isFulltime = 8; // Domestic only
}

message generateShadowIDRes {
  string tenant = 1;
  string requestShadowID = 2;
  string newShadowID = 3;
}

message encryptedPIIReq {
  string tenant = 1;
  string requesterShadowID = 2; // Who request PII encryption?
  string role = 3; // What is the role of the requester? (e.g. central_admin, staff, student)
  string ownerShadowID = 4; // Who is the Genuine Owner?
  string firstname = 5;
  string lastname = 6; 
  string DOB = 7; 
  string phone = 8; 
  string uniEmail = 9; 
  string personalEmail = 10; 
  string address = 11; 
  string uniID = 12;
  string nationalID = 13;
  string nationality = 14;
  string passportID = 15;
}

message encryptedPIIRes {
  string tenant = 1;
  string requesterShadowID = 2;
  bytes encryptedPIIBlob = 3;
  bool status = 4;
  optional string errorMessage = 5;
}

message decryptPIIReq {
  string tenant = 1;
  string requesterShadowID = 2;
  string requesterPosition = 3;
  string role = 4;
  string ownerShadowID = 5;
  string reason = 6;
}

message decryptPIIRes {
  string tenant = 1;
  bool isAuthorised = 2;
  bool success = 3;
  optional string errorMessage = 4;
}

message hashSearchKeyReq {
  string tenant = 1;
  string requesterShadowID = 2; // Record who request?
  string role = 3; // What is the role of the requester? (e.g. central_admin, staff, student)
  string ownerShadowID = 4; // Who owns PII?
  string name = 5;
  string uniEmail = 6;
  string DOB = 7;
  string uniID = 8;
}

message hashSearchKeyRes {
  string tenant = 1;
  bytes hashedName = 2;
  bytes hashedUniEmail = 3;
  bytes hashedDOB = 4;
  bytes hashedUniID = 5;
}

message revokePIIReq {
  string tenant = 1;
  string requestShadowID = 2;
  string ownerShadowID = 3;
  string requesterPosition = 4;
  string role = 5;
  bytes evidences = 6;
  string reason = 7;
}

message revokePIIRes {
  string tenant = 1;
  google.protobuf.Timestamp timestamp = 2;
  bool status = 3;
  bool isAuthority = 4; // Refer to the requester has authority to revoke PII or not.
  string responseMessage = 5;
  bool isIllegal = 6; // The reason related to the PII owner's illegal act or not, such as impersonate or forged government documents.
}

message validateIdentityReq {
  string tenant = 1;
  string requesterShadowID = 2; 
  string requesterPosition = 3;
  bytes hashedUniID = 4;
  bytes hashedName = 5;
  optional bytes hashedUniEmail = 6;
  optional bytes hashedDOB = 7;
}

message validateIdentityRes {
  string tenant = 1;
  string requesterShadowID = 2;
  bool isAuthorised = 3;
  bool success = 4;
  optional string shadowID = 5;
  string errorMessage = 6;
}